### ISSUE TITLE
Add read both lag and correlation value from linear correlation vmp

### ISSUE THREAD

**Issue by kenshukoiso** [ofgulban/bvbabel#49]
Hi Faruk,

I would like to read both lag and correlation value from a vmp file from linear correlation analysis. 
Currently, when I read the vmp file, I get only a matrix of lag value. 
However, I would like to get correlation map as well to mask my ROI.

Thank you so much in advance.
Kenshu

**Comment by ofgulban** [comment]
@kenshukoiso thanks for opening this issue. It turns out that the data was read correctly. However, the key detail was that the floating numbers were encoding the lags and correlation values at the same time. For instance a map read with value `15.3632` contains both lag information `15` and correlation coefficient `0.3632`.

After discovering this, I have now modified the VMP reader to spit out two maps instead of one only if the VMP map is a lag correlation map. 

So, please update your bvbabel and try again.

**Comment by kenshukoiso** [comment]
Thanks a lot, Faruk for your investigation and for updating the script super fast!!
